[package]
name = "engine-drc"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
domain-core = { path = "../domain-core" }
engine-geometry = { path = "../engine-geometry" }
foundation-core = { path = "../foundation-core" }
engine-physics = { path = "../engine-physics" }
rayon.workspace = true
serde.workspace = true

[lints]
workspace = true
