[package]
name = "engine-simulation"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
rayon = "1.8"
domain-core = { path = "../domain-core" }
foundation-core = { path = "../foundation-core" }
serde.workspace = true

[lints]
workspace = true
